[CR-204] Have the SendingMessage event include the original exception
MindscapeHQ/raygun4net pull request #434
Opened 2020-07-17 02:11 UTC by mduncan26

Update the `SendingMessage` event to include the original exception alongside the `RaygunMessage` object. This allows customers to perform further operations on the exception to extract contextual information only available on the exception.

2020-07-21 00:00 UTC, samuel-holt submitted a review, later dismissed
:+1: This change seems straightforward, nice work

2020-07-21 00:48 UTC, MattByers submitted a review, later dismissed

2020-07-21 02:12 UTC, QuantumNightmare requested changes
I have pointed out some methods that now require the new Exception parameter as they don't specify a default value, and I believe this would cause a breaking change.

I'm also going to point out this [somewhat related blog post](https://haacked.com/archive/2010/08/10/versioning-issues-with-optional-arguments.aspx/) around being careful when using optional parameters. It suggests that adding optional parameters to an existing method can cause runtime exceptions if an application has not been compiled, but has a new version of a client library that has added optional parameters to existing methods. I would expect applications to typically be compiled when upgrading to newer versions of client libraries though, so maybe it's not a concern for us.

2026-07-15 00:50 UTC, phillip-haydon commented
Superseded by `IMessageBuilder`, which provides access to the exception and can flag the resulting message for cancellation before it is sent.

2026-07-15 00:50 UTC, closed without merging