Updated environment information
MindscapeHQ/raygun4net pull request #496
Opened 2023-09-27 15:42 UTC by phillip-haydon

- Fixed Environment Information Memory
- Added cache for Environment Information to reduce overhead
- Added support for Environment Information on Windows/Linux/MacOS
- Changed CPU / OS information to be more accurate / understandable

2023-09-29 02:10 UTC, xenolightning requested changes

2023-09-29 02:10 UTC, xenolightning commented on Mindscape.Raygun4Net.NetCore.Common/Builders/RaygunEnvironmentMessageBuilder.cs
> +    private static readonly RaygunEnvironmentMessage CachedMessage = new RaygunEnvironmentMessage();
The only thing I can think of here - that by caching the message - we do open ourselves up to that private field being modified outside the `Build()` method.

Because it's the same reference returned I could be a bad person do something like 

```
RaygunEnvironmentMessageBuilder.Build(_).OSVersion = "this.phil"
```

And that would cause the OSVersion to be modified for all following reports..? Maybe there's a way to make this immutable?

![image](https://github.com/MindscapeHQ/raygun4net/assets/6000196/a09c2e6c-3ba6-4464-8597-4ddef97c2fab)

2023-10-05 03:41 UTC, phillip-haydon commented on Mindscape.Raygun4Net.NetCore.Common/Builders/RaygunEnvironmentMessageBuilder.cs
> +    private static readonly RaygunEnvironmentMessage CachedMessage = new RaygunEnvironmentMessage();
Now returning a new object to avoid the original being modified.

2023-10-08 19:09 UTC, xenolightning commented on Mindscape.Raygun4Net.NetCore.Common/Builders/RaygunEnvironmentMessageBuilder.cs
> +    private static readonly RaygunEnvironmentMessage CachedMessage = new RaygunEnvironmentMessage();
I like it 😎

2023-10-08 19:10 UTC, xenolightning approved these changes

2023-10-09 01:16 UTC, merged