[CS-55] Dont block sending
MindscapeHQ/raygun4net pull request #501
Opened 2023-11-19 23:04 UTC by darcythomas

DRAFT Looking for comments/feedback

Context: https://raygun.atlassian.net/browse/CS-55

Sending to RG in come cases seems to be blocking (the UI thread in RG4MAUI)

Sorry: there is some code weeding noise in there too.

2023-11-19 23:04 UTC, darcythomas commented on Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs
> +    {
Magic here

2023-11-21 01:43 UTC, xenolightning requested changes
Just a couple of comments/questions

2023-11-21 01:43 UTC, xenolightning commented on Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs
> +        await SendInternal(raygunMessage);
We should `ConfigureAwait(false)` this? To avoid a deadlock if say a UI thread raises this directly when throwing is on?

2023-11-21 01:43 UTC, xenolightning commented on Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs
> +    protected readonly RaygunSettingsBase Settings;
We might need to bump a major version if we change this, it's technically a public api change?

2023-11-21 01:43 UTC, xenolightning commented on Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs
> +        await SendInternal(raygunMessage);
It might not matter because the actual async operation is also configured, but could be safe guard

2023-11-21 01:43 UTC, xenolightning commented on Mindscape.Raygun4Net.NetCore.Common/FireAndForget.cs
> +    internal static Action<string> DebugLog { get; set; } = message => { /* NOOP by default */};
Is this property meant to be something that is user configurable? I note that it's not settable in the public api surface, and we don't provide a way to override it?

2023-11-21 02:07 UTC, darcythomas commented on Mindscape.Raygun4Net.NetCore.Common/FireAndForget.cs
> +    internal static Action<string> DebugLog { get; set; } = message => { /* NOOP by default */};
Currently we have a if (_settings.ThrowOnError) for debugging.

However that is pretty heavy handed and would not work where this is used because Fire.AndForget explicitly swallows any errors.

I have ideas for making a  public debug log (even if we tag it  that we make no guaranteed to support it etc)
Similar to what we have in raygun4js.


I would also like to have some on onboarding setup debug helper (maintained API) (e.g., you apikey is empty, invalid, there is no network connection etc)


That is all future direction stuff.
This is just enough for us to have a way of debugging

2023-11-21 02:08 UTC, darcythomas commented on Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs
> +    protected readonly RaygunSettingsBase Settings;
Reverted

2023-11-21 02:09 UTC, darcythomas commented on Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs
> +        await SendInternal(raygunMessage);
Should not matter, but since we don't want to mess up someone else's app. Better safe than sorry.

2023-12-20 00:44 UTC, darcythomas commented
Closing for now

2023-12-20 00:44 UTC, closed without merging