Cross Platform global exception handling
MindscapeHQ/raygun4net pull request #504
Opened 2024-01-12 02:30 UTC by xenolightning

Add low level global hooks for unhandled events across multiple platforms.

This should solve the issues with not catching unhandled exceptions.

There is also no workload requirements due to using reflection everywhere.

Very much a PR looking for review feedback

2024-01-12 02:39 UTC, xenolightning commented on Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs
> +      UnhandledExceptionBridge.OnUnhandledException += OnApplicationUnhandledException;
A big change here is always subscribing to the unhandled exceptions. So the callbacks are fired each and everytime.

They are then filtered out before sending.

This may impact performance - but since it's on unhandled exceptions, when the app is misbehaving or about to crash it should be fine???

2024-01-12 02:40 UTC, xenolightning commented on global.json
> +    "version": "7.0.0",
this can be put back to 6.0.0 - was done for maui testing

2024-01-12 02:40 UTC, xenolightning commented on Mindscape.Raygun4Net.WebApi/Mindscape.Raygun4Net.WebApi.csproj
> +      <SubType>Component</SubType>
Remove

2024-01-14 19:44 UTC, phillip-haydon requested changes
Needs more braces :D

2024-01-14 19:44 UTC, phillip-haydon commented on Mindscape.Raygun4Net.NetCore.Common/Messages/RaygunClientMessage.cs
> +      ClientVersion = informationalVersion ?? "8.1.0";
Is there any reason why we would never get a value here other than testing? Worried this might be something we need to manually update all the time.

2024-01-14 19:44 UTC, phillip-haydon commented on Mindscape.Raygun4Net.NetCore.Common/Messages/RaygunClientMessage.cs
> +      ClientVersion = informationalVersion ?? "8.1.0";
(the fix its for is good tho)

2024-01-14 19:44 UTC, phillip-haydon commented on Mindscape.Raygun4Net.NetCore.Common/Platforms/AndroidPlatform.cs
> +          return false;
Missing braces!

2024-01-14 19:44 UTC, phillip-haydon commented on Mindscape.Raygun4Net.NetCore.Common/Platforms/ApplePlatform.cs
> +          return false;
Missing braces!

2024-01-14 19:44 UTC, phillip-haydon commented on Mindscape.Raygun4Net.NetCore.Common/Platforms/WindowsPlatform.cs
> +          return false;
👀

2024-01-14 19:44 UTC, phillip-haydon commented on Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs
> +        return;
👀

2024-01-14 19:44 UTC, phillip-haydon commented on Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs
> +#if UNHANDLED_EXCEPTIONS_SUPPORT
Is this still required? If we are doing reflection to wire things up can we not just set it to wire up always even if by default its an empty handler? Wondering if it helps clean up the code and/or prevent the requirement of precomplication flags.

2024-01-14 19:49 UTC, xenolightning commented on Mindscape.Raygun4Net.NetCore.Common/Platforms/AndroidPlatform.cs
> +          return false;
👿

2024-01-14 20:13 UTC, xenolightning commented on Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs
> +#if UNHANDLED_EXCEPTIONS_SUPPORT
Have removed pre-processor def's

The targets always include this particular flag anyway

2024-01-14 20:15 UTC, xenolightning commented on Mindscape.Raygun4Net.NetCore.Common/Messages/RaygunClientMessage.cs
> +      ClientVersion = informationalVersion ?? "8.1.0";
It's unlikely - I set it as a fallback so we have _something_. In the unlikely scenario we are not able to use reflection.

The last value set was 6.5.x so it wasn't updated as it was.

If we update it, cool, if we don't, cool.

2024-01-14 21:00 UTC, phillip-haydon commented on Mindscape.Raygun4Net.NetCore.Common/Platforms/AndroidPlatform.cs
> +          return false;
🤤

2024-01-14 21:22 UTC, phillip-haydon approved these changes
:shipit:

2024-01-15 19:14 UTC, phillip-haydon submitted a review, later dismissed
:shipit:

2024-01-15 20:30 UTC, phillip-haydon approved these changes
:shipit: NOW! No more additions please :D

2024-01-15 20:32 UTC, merged

2024-01-15 20:32 UTC, xenolightning commented
Changes to be rolled into a later 8.2.0 nuget release with support for httpclient and timeouts

2024-02-01 21:26 UTC, Obi-Dann commented on Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs
> +      UnhandledExceptionBridge.OnUnhandledException += OnApplicationUnhandledException;
In the context of AspNetCore, there will be multiple instances of RaygunClient created for each HttpContext. Every single one of these instances will subscribe to OnUnhandledException.
None of those instances will be garbage collected because currently RaygunClientBase is not disposable and never unsubscribes from OnUnhandledException.
I suspect in those scenarios, an unhandled rejection will be send as many times as many clients were ever created.
What is the expected lifetime of RaygunClient? This change assumes it's a singleton, but it's not used like a singleton in AspNetCore.
It's not fine