Add breadcrumbs to Raygun4Net.NetCore/AspNetCore
MindscapeHQ/raygun4net pull request #516
Opened 2024-02-16 03:17 UTC by ProRedCat

This brings Breadcrumbs from Raygun4Net4 to the NetCore libraries, some features are removed such as breadcrumb levels, optional stack frame (always included now), and internal error throwing.

- Adds breadcrumbs to Raygun4Net.NetCore/AspNetCore. Uses AsyncLocal with the async context set at the middleware layer for AspNetCore so that breadcrumbs are in scope only for the request they belong to. 
AsyncLocal is the default storage, but it can be set to a global scope (InMemoryBreadcrumbStorage) - Raygun4Maui will use the global scope version.

- Adds packing script to run on MacOS and Linus (translation of existing powershell script) for local development

2024-02-18 19:32 UTC, xenolightning requested changes
We should also be writing tests to cover usage scenarios

2024-02-18 19:32 UTC, xenolightning commented on Mindscape.Raygun4Net.AspNetCore/RaygunClient.cs
> +        .SetBreadcrumbs(Breadcrumbs.Any() ? Breadcrumbs.ToList() : null)
Could be simply `Breadcumbs?.ToList()`, it's either empty, got stuff, or null.

Any(), ToList() "enumerates" the collection twice. Even though the Any short circuits it's more efficient and concise doing it just once.

2024-02-18 19:32 UTC, xenolightning commented on Mindscape.Raygun4Net.NetCore.Common/Breadcrumbs/RaygunBreadcrumb.cs
> +    private static readonly DateTime UnixEpoch = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);
We usually follow this convention for class layout.

const/statics, readonly, fields, properties, ctors, methods

2024-02-18 19:32 UTC, xenolightning commented on Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs
> +    protected static RaygunBreadcrumbs Breadcrumbs;
protected static is a weird combination - not seen too often.

Does it need to be static?

2024-02-18 19:39 UTC, phillip-haydon commented on Mindscape.Raygun4Net.NetCore.Common/Breadcrumbs/Enums.cs
> +    Manual
This seems pointless, can just use the word directly in the code for the type for now. As a side you can use `nameof(...)` on the enum instead of `ToString()`, its faster and cleaner.

2024-02-18 19:40 UTC, phillip-haydon commented on Mindscape.Raygun4Net.NetCore.Common/Breadcrumbs/Enums.cs
> +  public enum RaygunBreadcrumbLevel
Can we ditch this entirely for now? Lets not entrance ourselves into `Levels` when we may decide to not support this at all.

2024-02-18 19:48 UTC, xenolightning commented
Err I seemed to have commented on an older commit, let me look again

2024-02-18 19:53 UTC, xenolightning commented on Mindscape.Raygun4Net.AspNetCore/RaygunAspNetMiddleware.cs
> +      if (RaygunBreadcrumbs.Storage is AsyncLocalBreadcrumbStorage)
I would probably look to change this.

Either create two interfaces `IContextAwareStorage : IStorage` or use a default implementation on the interface. I think the first might be slightly cleaner

2024-02-18 19:54 UTC, xenolightning commented on Mindscape.Raygun4Net.NetCore.Common/Breadcrumbs/IRaygunBreadcrumbStorage.cs
> +    IList<RaygunBreadcrumb> Dump();
Dump was just my human words. The method should probably get `ToList()` or `GetAll()`

2024-02-19 20:19 UTC, ProRedCat commented on Mindscape.Raygun4Net.AspNetCore/RaygunAspNetMiddleware.cs
> +      if (RaygunBreadcrumbs.Storage is AsyncLocalBreadcrumbStorage)
Created IContextAwareStorage which provices BeginContext and EndContext. AsyncLocalBreadcrumbStorage implements this now

2024-02-19 20:19 UTC, ProRedCat commented on Mindscape.Raygun4Net.NetCore.Common/Breadcrumbs/Enums.cs
> +  public enum RaygunBreadcrumbLevel
Levels have now been removed, and the settings in RaygunSettingsBase were removed as well

2024-02-19 20:20 UTC, ProRedCat commented on Mindscape.Raygun4Net.NetCore.Common/Breadcrumbs/Enums.cs
> +    Manual
Removed the enum, it's now hardcoded for manual breadcrumb type

2024-02-19 20:20 UTC, ProRedCat commented on Mindscape.Raygun4Net.NetCore.Common/Breadcrumbs/IRaygunBreadcrumbStorage.cs
> +    IList<RaygunBreadcrumb> Dump();
Replaced with ToList

2024-02-19 20:58 UTC, phillip-haydon commented
Tagging #465

2024-02-22 02:01 UTC, phillip-haydon commented on Mindscape.Raygun4Net.AspNetCore/RaygunAspNetMiddleware.cs
> +
:+1: this is much cleaner than the casting from before.

2024-02-22 02:04 UTC, phillip-haydon commented on Mindscape.Raygun4Net.NetCore.Common/Breadcrumbs/RaygunBreadcrumb.cs
> +      Timestamp = (long)(DateTime.UtcNow - UnixEpoch).TotalMilliseconds;
I'm pretty sure you can assign these directly to the props

```
public IDictionary<string, object> CustomData { get; set; } = new ();
```

Cleans up and removes the need to have the explicit ctor.

2024-02-22 02:06 UTC, phillip-haydon commented on Mindscape.Raygun4Net.NetCore.Common/RaygunSettings.cs
> +using Mindscape.Raygun4Net.Breadcrumbs;
Is this un-used? There's no other changes in this file.

2024-02-22 02:07 UTC, phillip-haydon commented on Mindscape.Raygun4Net.NetCore.Tests/RaygunBreadcrumbsTests.cs
> +
My OCD kicking off, whitespace!

2024-02-22 02:08 UTC, phillip-haydon commented on pack-all.sh
👍 thanks for converting this to a shell script for when we are using macOS/Linux.

2024-02-22 02:09 UTC, ProRedCat commented on Mindscape.Raygun4Net.NetCore.Common/RaygunSettings.cs
> +using Mindscape.Raygun4Net.Breadcrumbs;
Oops you're right, I had the levels in there beforehand which pulled in that import

2024-03-11 18:23 UTC, phillip-haydon approved these changes
Don't forget to update docs to include this new feature

2024-03-12 02:00 UTC, phillip-haydon approved these changes
Looking good now, the resizing looks cleaner. Get @xenolightning to cast his eye over it then we can get it in.

2024-03-12 20:06 UTC, xenolightning approved these changes
Yeah this looks solid 👍🏼

2024-03-12 20:22 UTC, merged