Remove the usage of LocalThread in .NET Framework versions
MindscapeHQ/raygun4net pull request #517
Opened 2024-02-19 00:06 UTC by phillip-haydon

Sometimes a null-ref exception occurs when building the message due to the fields being persistent in the RaygunClient when using SendInBackground. 

This PR makes the data scoped to the function and passed through.

Also cleaned up some methods now that the version of C# has been updated, we can use optional parameters.

2024-02-19 01:09 UTC, xenolightning requested changes
The code itself look fine.

I think a covering test would be ideal if possible

2024-02-19 19:48 UTC, phillip-haydon commented
Hard to write unit tests because HttpServer doesn't fill in the HttpContext, running it up in IIS Express / IIS to test tho everything seems to be working fine.

2024-02-21 01:25 UTC, xenolightning commented
Happy to move forward, due to NETFX being a pain to unit test

2024-02-21 01:25 UTC, xenolightning submitted a review, later dismissed

2024-02-22 00:23 UTC, xenolightning approved these changes

2024-02-22 00:29 UTC, merged