WIP - Add support for offline storage of errors to Raygun4Net Core
MindscapeHQ/raygun4net pull request #530
Opened 2024-05-14 03:01 UTC by xenolightning

This is an early implementation to allow for early feedback and suggestions

2024-05-15 02:34 UTC, xenolightning commented
@phillip-haydon this is mostly ready for review.

Can review the approach, and the linkage to the client for now

There is a singleton background worker, and it is wired up to a cache - which should also be a singleton.

The clients (not a singleton yet) can then use the offline store to put failed crash reports, to be picked up by the background worker at a later date.

If it fails to send, then it does not remove the cached error from the disk

2024-05-23 03:34 UTC, PanosNB reviewed
Lot's of good work! Some questions on my end

2024-05-23 03:34 UTC, PanosNB commented on Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs
> +        if (!hasMessageBeenStored)
Should we move this to finally such that you don't to the offline write call twice?

2024-05-23 03:34 UTC, PanosNB commented on Mindscape.Raygun4Net.NetCore.Common/Storage/CachedCrashReportBackgroundWorker.cs
> +  public static void Start()
Do we need this public? What happens if someone calls it outside the static initializer?

2024-05-23 03:34 UTC, PanosNB commented on Mindscape.Raygun4Net.NetCore.Common/Storage/CachedCrashReportBackgroundWorker.cs
> +  public static void Start()
Or if we do need it exposed, should have conditional logic in case _isRunning is already true?

2024-05-23 03:34 UTC, PanosNB commented on Mindscape.Raygun4Net.NetCore/Storage/FileSystemCrashReportCache.cs
> +        using var fileStream = new FileStream(crashFile, FileMode.Open, FileAccess.Read);
Is there implicit scope for the usings here? Where do they close?

2024-05-23 03:34 UTC, PanosNB commented on Mindscape.Raygun4Net.NetCore/Storage/FileSystemCrashReportCache.cs
> +  public virtual async Task<List<CrashReportCacheEntry>> GetAll(CancellationToken cancellationToken)
Isn't this too risky of causing an out of memory? Or the very least thrashing the GC? Why do we need them all fetched in memory and we don't just send them to Raygun?

2024-05-23 03:34 UTC, PanosNB commented on Mindscape.Raygun4Net.NetCore/Storage/FileSystemCrashReportCache.cs
> +      using var fileStream = new FileStream(filePath, FileMode.Create);
Is it one file per crash?

2024-05-23 03:41 UTC, xenolightning commented on Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs
> +            hasMessageBeenStored = await SaveMessageToOfflineCache(payload, apiKey, cancellationToken);
The idea here is that we only want to store crashes when raygun is unreachable, which will be any http errors in the 5xx range.

We don't want to store anything from 2xx or 4xx, because that signals raygun was alive, and accepted or rejected the payload.

2024-05-23 03:42 UTC, xenolightning commented on Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs
> +        if (!hasMessageBeenStored)
Yeah that might tidy this up a little, I'll take a look.

We need to send when 5xx or when there's a network outage

2024-05-23 03:43 UTC, xenolightning commented on Mindscape.Raygun4Net.NetCore.Common/Storage/CachedCrashReportBackgroundWorker.cs
> +  public static void Start()
I want to give users the ability to turn on/off the background worker if they want to

2024-05-23 03:59 UTC, xenolightning commented on Mindscape.Raygun4Net.NetCore/Storage/FileSystemCrashReportCache.cs
> +      using var fileStream = new FileStream(filePath, FileMode.Create);
Yeah that's the idea, it's easier to manage what has/hasn't been sent without loading in entire collections into memory.

We'd want to limit the number of files etc... though

2024-05-23 03:59 UTC, xenolightning commented on Mindscape.Raygun4Net.NetCore/Storage/FileSystemCrashReportCache.cs
> +        using var fileStream = new FileStream(crashFile, FileMode.Open, FileAccess.Read);
They close at the end of the scope yep

2024-05-23 04:00 UTC, xenolightning commented on Mindscape.Raygun4Net.NetCore/Storage/FileSystemCrashReportCache.cs
> +  public virtual async Task<List<CrashReportCacheEntry>> GetAll(CancellationToken cancellationToken)
I did think about optimizing this to lazy load / stream the results in, but that could get awkward if there's a lot of files being continuously being created.

Certainly should be altered before making it production ready though

2024-05-23 04:02 UTC, xenolightning commented on Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs
> +        if (_settings.ThrowOnError)
It is yeah, it's actually original code, but I changed the method too much the diff doesn't show it well

2024-05-28 00:50 UTC, xenolightning reviewed
Tagged phill to review the public api surface in specific areas

2024-05-28 00:50 UTC, xenolightning commented on Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs
> +    protected RaygunClientBase(RaygunSettingsBase settings, HttpClient client, ICrashReportCache crashReportCache)
@phillip-haydon

2024-05-28 00:50 UTC, xenolightning commented on Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs
> +        _crashReportCache = crashReportCache;
@phillip-haydon

2024-05-28 00:50 UTC, xenolightning commented on Mindscape.Raygun4Net.NetCore.Common/Storage/CachedCrashReportBackgroundWorker.cs
> +public static class CachedCrashReportBackgroundWorker
@phillip-haydon

2024-05-28 00:50 UTC, xenolightning commented on Mindscape.Raygun4Net.NetCore/Storage/FileSystemCrashReportCache.cs
> +public class FileSystemCrashReportCache : ICrashReportCache
@phillip-haydon

2024-05-28 01:13 UTC, phillip-haydon approved these changes
Only 1 comment..

2024-05-28 01:35 UTC, xenolightning commented on Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs
> +    protected RaygunClientBase(RaygunSettingsBase settings, HttpClient client, ICrashReportCache crashReportCache)
So this is where I started, but the DI extensions is only in the asp.net project, or maui etc...

Not the base library, so it's not always available in it's current form.

Ideally we should have a bunch of services in the container and construct a singleton from the MS DI container, but that's.... a while away

2024-05-28 23:05 UTC, xenolightning commented on Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs
> +          if ((int)response.StatusCode >= 500)
Status code is an enum, and we can't do gt / lt checks on enum values. 

The enum value is integer backed though

2024-05-28 23:09 UTC, xenolightning commented on Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs
> +          if ((int)response.StatusCode >= 500)
I stand corrected! We can do an enum compare hahah.

I've just never done it before, and assumed it needed to be downcasted to an int

Will push a change

2024-05-28 23:26 UTC, xenolightning commented on Mindscape.Raygun4Net.NetCore.Tests/RaygunMessageBuilderTests.cs
> +          //"* *",
Bleh, need to undo

2024-05-29 20:47 UTC, ProRedCat commented on Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs
> +        CachedCrashReportBackgroundWorker.SetSendCallback(SendPayloadAsync);
Will we have any lifetime issues with this delegate? #529 might have been because of `WeakReference` but just want to make sure that we don't have that happen here

2024-05-29 22:15 UTC, xenolightning commented on Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs
> +        CachedCrashReportBackgroundWorker.SetSendCallback(SendPayloadAsync);
It will keep one client alive at all times, I'm working on changing the way this hooks into the client.

But it won't change the fact we need a single client alive to send the payloads - so sadly yeah, it has to be like this until we look at making the client a singleton, and can have a bit more of a robust link

2024-06-04 21:44 UTC, PanosNB approved these changes
All good! A couple of non-blocking comments

2024-06-04 21:44 UTC, PanosNB commented on Mindscape.Raygun4Net.NetCore.Common/Offline/OfflineStoreBase.cs
> +#nullable  enable
There are two spaces here (Don't be blocked on this, haha)

2024-06-04 21:44 UTC, PanosNB commented on Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs
> +        var shouldStoreMessage = response is null || response.StatusCode >= HttpStatusCode.InternalServerError;
Instead of a greater-than-check in here, should we add a static method to assess if the status code is valid? Also, the greater-than check is a bit unintuitive. Should we do not in X?

2024-06-04 21:45 UTC, xenolightning commented on Mindscape.Raygun4Net.NetCore.Common/Offline/OfflineStoreBase.cs
> +#nullable  enable
Doh, I'll fix it

2024-06-04 21:45 UTC, xenolightning commented on Mindscape.Raygun4Net.NetCore.Common/Offline/OfflineStoreBase.cs
> +      return;
Yeah, bad habit, doesn't conform to out styles either, will fix

2024-06-04 22:58 UTC, xenolightning commented on Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs
> +        var shouldStoreMessage = response is null || response.StatusCode >= HttpStatusCode.InternalServerError;
I already check that it's valid on line 542.

That throws an exception if it's invalid

We could check that it's not in 500, 501, 502, 503, 504 ...

The RFC spec says that anything starting with a 5 is a server error, and if that's the case we should store for later, for brevity checking >= is the same as checking the first digit of the response is a 5(xx)

I'll add a comment, but checking a list is more error prone for unexpected 5xx error codes, and provides little value

2024-06-04 23:00 UTC, phillip-haydon requested changes
><

2024-06-04 23:03 UTC, xenolightning commented on Mindscape.Raygun4Net.NetCore/Storage/FileSystemCrashReportStore.cs
> +      Directory.CreateDirectory(_storageDirectory);
Nah, it just doesn't create a directory if it exists, and returns the directoryinfo of the existing directory

2024-06-04 23:04 UTC, xenolightning commented on Mindscape.Raygun4Net.NetCore/Storage/LocalApplicationDataCrashReportStore.cs
> +  private static string CreateUniqueDirectory()
I'll rename the method to directory name :)

2024-06-04 23:04 UTC, xenolightning commented on Mindscape.Raygun4Net.NetCore/RaygunClient.cs
Yes, and the validate api key too

2024-06-05 20:06 UTC, PanosNB approved these changes
Looks good to me!

2024-06-05 21:54 UTC, xenolightning commented on Mindscape.Raygun4Net.NetCore.Common/RaygunSettingsBase.cs
> +  public OfflineStoreBase OfflineStore { get; set; }
@phillip-haydon,

@ProRedCat made a good point in the maui space

This isn't configurable as a "setting", think appsettings.json

Do we want to revisit maybe putting it back into the constructor?

2024-06-05 22:54 UTC, phillip-haydon approved these changes

2024-06-07 01:57 UTC, xenolightning commented on Mindscape.Raygun4Net.NetCore.Common/RaygunSettingsBase.cs
> +  public OfflineStoreBase OfflineStore { get; set; }
resolution: leave it as a setting for now and just require code config because of the "class" nature of it

2024-06-07 01:57 UTC, merged