Change UnobservedTaskException from being tagged as UnhandledException to UnobservedTaskException
MindscapeHQ/raygun4net pull request #548
Opened 2024-11-05 22:15 UTC by ProRedCat

2024-11-05 22:55 UTC, QuantumNightmare requested changes
A couple of comments to consider

2024-11-05 22:55 UTC, QuantumNightmare commented on Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs
> +      Send(exception, new List<string> { tag });
Looks like the constant UnhandledExceptionTags is no longer used because of this change and so should be deleted too.

2024-11-05 22:55 UTC, QuantumNightmare commented on Mindscape.Raygun4Net.NetCore.Common/UnhandledExceptionBridge.cs
> +      public void Invoke(Exception exception, bool isTerminating, string tag)
Perhaps this class is not intended to be used by customers, but this is technically a breaking change due to it being public. (Same as all the public methods above). Shall we instead make an overload for this method and change the other methods above to not have a tag passed in (if that argument is never used) and just pass the string literal from with their method bodies?

2024-11-05 22:55 UTC, ProRedCat commented on Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs
> +      Send(exception, new List<string> { tag });
Had that in mind, kept it in case we needed it but likely we do not anymore

2024-11-05 23:04 UTC, ProRedCat commented on Mindscape.Raygun4Net.NetCore.Common/UnhandledExceptionBridge.cs
> +      public void Invoke(Exception exception, bool isTerminating, string tag)
Should be addressed now, let me know what you think

2024-11-06 13:55 UTC, velocitysystems commented on Mindscape.Raygun4Net.NetCore.Common/UnhandledExceptionBridge.cs
> +      TaskScheduler.UnobservedTaskException += (sender, args) => { RaiseUnhandledException(args.Exception,false, "UnobservedTaskException"); };
@ProRedCat I believe `UnobservedTaskException` may always (or _nearly_ always) raise an `AggregateException`. 
If there is only one inner exception this should _really_ be unboxed. This appears to be the current behavior of the MAUI Xamarin provider.

2024-11-06 20:11 UTC, velocitysystems commented on Mindscape.Raygun4Net.NetCore.Common/UnhandledExceptionBridge.cs
> +      TaskScheduler.UnobservedTaskException += (sender, args) => { RaiseUnhandledException(args.Exception,false, "UnobservedTaskException"); };
This change looks good @ProRedCat. What about `AggregateException`'s which are _not_ unobserved task exceptions (handled + unhandled) - Will they also be unwrapped?

2024-11-06 20:13 UTC, ProRedCat commented on Mindscape.Raygun4Net.NetCore.Common/UnhandledExceptionBridge.cs
> +      TaskScheduler.UnobservedTaskException += (sender, args) => { RaiseUnhandledException(args.Exception,false, "UnobservedTaskException"); };
In this case right now it's only the UnobservedTaskExceptions, will have a chat with some other around handled + unhandled

2024-11-06 20:56 UTC, QuantumNightmare commented on Mindscape.Raygun4Net.NetCore.Common/UnhandledExceptionBridge.cs
> +      public void Invoke(Exception exception, bool isTerminating, string tag)
Ah yes, I didn't see this code is in a nested private class

2024-11-06 21:01 UTC, QuantumNightmare approved these changes
Thanks for the changes

2024-11-12 20:42 UTC, ProRedCat commented on Mindscape.Raygun4Net.NetCore.Common/UnhandledExceptionBridge.cs
> +      TaskScheduler.UnobservedTaskException += (sender, args) => { RaiseUnhandledException(args.Exception,false, "UnobservedTaskException"); };
Observability for others: We do have a feature for automatically unwrapping exceptions.

This is done through `_raygunClient.AddWrapperExtensions(typeof(AggregateException))`

2024-11-12 21:25 UTC, merged