Add MS Logger support
MindscapeHQ/raygun4net pull request #553
Opened 2024-12-08 21:56 UTC by phillip-haydon

New Mindscape.Raygun4Net.Extensions.Logger for supporting MSLogger.

Introduces a new IMessageBuilder to allow customisation of messages without needing api changes or code changes to support things. 

This should fix #526 which would allow adding and registering a new class like:

```csharp
public class DefaultTags : IMessageBuilder
{
  public Task<RaygunMessage> Apply(RaygunMessage message, Exception exception)
  {
    message.Details.Tags.Add("DefaultTag");
    
    return Task.FromResult(message);
  }
}
```

And registering it during startup

```csharp
builder.Services.AddRaygun(settings =>
{
  settings.ApiKey = "*your_api_key*";
});
builder.Services.AddSingleton<IMessageBuilder, DefaultTags>();
```

Which would add the tag during the message building and submit with the default tag.

See [Mindscape.Raygun4Net.Extensions.Logging/README.md] for MSLogger info.

2024-12-08 22:00 UTC, phillip-haydon commented on .editorconfig
> +dotnet_diagnostic.IDE0290.severity = none
This disables suggesting primary constructors.

2024-12-08 22:00 UTC, phillip-haydon commented on .editorconfig
> +csharp_prefer_braces = true:error
Enforces `if` statements to have braces.

2024-12-08 22:01 UTC, phillip-haydon commented on Mindscape.Raygun4Net.AspNetCore/Builders/RaygunAspNetCoreResponseMessageBuilder.cs
> +    public static Task<RaygunResponseMessage> Build(HttpContext? context, RaygunSettings _)
No one should be accessing this except us, this is made async for consistency with the Request but will likely be moved into the message builder in the future.

2024-12-08 22:17 UTC, ProRedCat commented on Mindscape.Raygun4Net.Extensions.Logging/RaygunLogger.cs
> +      // Log the failure to send to Raygun - you might want to use a fallback logger here
Are these comments for us?

2024-12-08 22:31 UTC, phillip-haydon commented on Mindscape.Raygun4Net.Extensions.Logging/RaygunLogger.cs
> +      // Log the failure to send to Raygun - you might want to use a fallback logger here
Just github co-pilot putting weird shit in

2024-12-08 22:37 UTC, PanosNB requested changes
Great work! I have some concerns about introducing a breaking change by expecting the RaygunClient constructor to have that extra field. We shouldn't be introducing any, so let me know if I am mistaken :-)

2024-12-08 22:37 UTC, PanosNB commented on Mindscape.Raygun4Net.AspNetCore.Tests/Mindscape.Raygun4Net.AspNetCore.Tests.csproj
> +    <TargetFramework>net8.0</TargetFramework>
This is backwards compatible to 6?

2024-12-08 22:37 UTC, PanosNB commented on Mindscape.Raygun4Net.AspNetCore/RaygunClient.cs
> +  public RaygunClient(RaygunSettings settings, IRaygunUserProvider userProvider, IEnumerable<IMessageBuilder> messageBuilders) : base(settings, userProvider, messageBuilders)
So we no longer allow a RaygunClient to be constructed with `RaygunClient(RaygunSettings settings, IRaygunUserProvider userProvider)`? Doesn't this introduce a breaking change?

2024-12-08 22:37 UTC, PanosNB commented on Mindscape.Raygun4Net.Extensions.Logging/RaygunLogger.cs
> +    var message = formatter?.Invoke(state, exception);
Can we enforce non-null of the formatter parameter type instead of doing the null check here?

2024-12-08 22:37 UTC, PanosNB commented on Mindscape.Raygun4Net.Extensions.Logging/RaygunLoggerExtensions.cs
> +    options?.Invoke(settings);
What happens is configuration or options is passed as `null`?

2024-12-08 22:37 UTC, PanosNB commented on Mindscape.Raygun4Net.Extensions.Logging/RaygunLoggerProvider.cs
> +    if (_disposed)
Why don't we care about concurrent access to `_disposed` by someone calling `CreateLogger` and `Dispose` (below) about the same time?

2024-12-08 22:37 UTC, PanosNB commented on Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs
> +      : this(settings, DefaultClient, null, [])
Double check my concerns above about breaking changes

2024-12-08 22:37 UTC, PanosNB commented on Mindscape.Raygun4Net.NetCore/ApplicationBuilderExtensions.cs
> +    var existing = services.FirstOrDefault(x => x.ServiceType == typeof(IRaygunUserProvider));
Does this need to clear more than than one?

2024-12-08 22:45 UTC, phillip-haydon commented on Mindscape.Raygun4Net.NetCore/ApplicationBuilderExtensions.cs
> +    var existing = services.FirstOrDefault(x => x.ServiceType == typeof(IRaygunUserProvider));
I'm unsure, what is not clear about it?

2024-12-08 22:46 UTC, phillip-haydon commented on Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs
> +      : this(settings, DefaultClient, null, [])
This is calling the base-ctor, and its just adding a default so the main ctors pass it down

2024-12-08 22:47 UTC, phillip-haydon commented on Mindscape.Raygun4Net.Extensions.Logging/RaygunLogger.cs
> +    var message = formatter?.Invoke(state, exception);
Cannot, its not our interface, this comes from MS.

2024-12-08 22:48 UTC, phillip-haydon commented on Mindscape.Raygun4Net.AspNetCore.Tests/Mindscape.Raygun4Net.AspNetCore.Tests.csproj
> +    <TargetFramework>net8.0</TargetFramework>
Test project, so it doesn't matter.

2024-12-09 01:17 UTC, phillip-haydon commented on Mindscape.Raygun4Net.Extensions.Logging/RaygunLoggerExtensions.cs
> +    options?.Invoke(settings);
Then the base settings will be used. The new instance of the settings variable defines the default values, these are overridden by the configuration settings from appsettings.json, and further overridden by code level configuration bassed in as ōptions.

2024-12-09 01:20 UTC, phillip-haydon commented on Mindscape.Raygun4Net.NetCore/ApplicationBuilderExtensions.cs
> +    var existing = services.FirstOrDefault(x => x.ServiceType == typeof(IRaygunUserProvider));
We only want to ensure 1 is registered, so we can safely assume the one registered by the customer is the one used.

If they register outside of this helper, multiple implementations can be registered. When resolved it will take the last registration, so depending on if they register before or after us would dictate whose gets used.

2024-12-09 20:40 UTC, PanosNB approved these changes
This maintains backwards compatibility with the constructors, so all good on my end!

2024-12-10 00:31 UTC, PanosNB approved these changes
lgtm

2024-12-10 19:23 UTC, merged